
language: objective-c  #1
osx_image: xcode8.3 #2
xcode_workspace: Example/EPShapes.xcworkspace #3
xcode_scheme: EPShapes #4
xcode_sdk: iphonesimulator #5

script:
- open -b com.apple.iphonesimulator
- xcodebuild -project EPShapes.xcodeproj -scheme EPShapes -sdk iphonesimulator  -destination "platform=iOS Simulator,name=iPhone 7" build test


#https://github.com/ipraba/EPSignature
